### ISSUE TITLE
Inventory and Item Port

### ISSUE THREAD

**Issue by choi303** [kk-digital/kcg#152]
Inventory

- [x]  Create a component called Inventory. 
- [x] Items of it is entity.
- [x] Inventory have list of Item slots.
- [x] Make array for slots. And fill with items.
- [ ] Make a inventory tile.

Item
- [x] Item is an entity.
- [x] Make a item id, and name etc. Put in a local struct.
- [x] Load sprite of it.

**Comment by mororo250** [comment]
The mssings tasks are in #206
