### ISSUE TITLE
Unity Tool: Script for Testing "Pixel Perfect Camera"

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/kcg#30]
see:
- https://www.youtube.com/watch?v=Q9azj6lZ4Jw

Unit Script

In Assets/Script
- called PixelPerfectCameraTestTool

Draw a grid of 128x128 pixels
- alternating black and white
- ability to adjust size in Unity GUI

- has X position, Y position
- has option to follow mouse or fixed position
- option for float offset in X/Y for sub-pixel offset (added after snapping)
 
- Option for semi-transparency (alpha blending)
- centered on mouse
- snap to 1.0f/32 nearest pixel (32 pixels = 1.0f)
 
Option for changing
- number of pixels in square
- option for alpha level

**Comment by choi303** [comment]
Done.
