### ISSUE TITLE
Unity Mesh Bug

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/kcg#313]
Can't add component 'MeshRenderer' to text because such a component is already added to the game object!
UnityEngine.GameObject:.ctor (string,System.Type[])
Utility.Render:CreateText (UnityEngine.Transform,UnityEngine.Vector2,string,int) (at Assets/Source/Utility/Render.cs:187)
Utility.Render:DrawString (single,single,single,string,int,UnityEngine.Color,UnityEngine.Transform,int) (at Assets/Source/Utility/Render.cs:139)
FloatingText.FloatingTextDrawSystem:Draw (UnityEngine.Transform,int) (at Assets/Source/FloatingText/Systems/FloatingTextDrawSystem.cs:18)
Planet.PlanetState:Update (single,UnityEngine.Material,UnityEngine.Transform) (at Assets/Source/Planet/PlanetState.cs:244)
Planet.Unity.PlanetTest:Update () (at Assets/Scripts/PlanetTest.cs:70)

**Comment by mororo250** [comment]
I believe this has been fixed.
