### ISSUE TITLE
Library: FileLoading

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/kcg#42]
Write a new library for loading files in C#
- Called FileLoadingManager
- NameSpace FileLoader
- can be in /Assets/src/Utility/FileLoader

This is an object, for the loading of files into memory and assignment of a "FileId" integer for referencing a specific file asset. Assets can be unloaded or loaded from RAM, but the fileId for same file will also be the same. If file is modified, the file asset may be reloaded.

Every asset the game loads, goes through here

1> Dictionary of FileNames to FileId

2> An array of FileProperties structs

3> API for unloading file

```
Struct FileLoadingManager
- a map of filename to index
- a linear array of FileData entries
```

//FileData Properties
```
struct FileData

FileId
Filename // Filename and path string
Int64 Hash // 64 bit xxHash of image file
Int FileCreationTime // time of file modification
int FileSize //int, size on disc
int UsageCount //incremented by consumer applications
int ReloadCount //how many times file was reloaded
int DeleteCount //how many times file was deleted
int RefCount //just ref count
int LastUsed //unix seconds time from program startup
int CreationDate //unix seconds time since program creation to first load
int Loaded //true/false for whether data is loaded into memory

[]byte ByteArray
```
API:
- getting file Id from FileName
- get FileData pointer from filename
- get list of files in list that have been modified since creation
 
Note:
- we want a single byte data array
-- for FileData
-- for SpriteData

For memory mapped file cache

--- 

IGNORE BELOW

```
int Id //optional
int AssetType 
int ByteStart
int ByteLength
```

Later:
- order files by usage (sort by access)
- compact byte array (GC)
- expand byte array if not too

**Comment by wylanosorio** [comment]
**"This is an object, for the loading of files into memory"**
@haltingstate Is this going to read file(s) from the disk?
