### ISSUE TITLE
Setup Unit Testing with NSpec

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/kcg#50]
http://nspec.org/

- unit test in root directory
-- avoid having unity run the tests on recompile

- how to run/build unit tests cross platform
- how to allow Travis to run unit tests

- how to unit test for code that depends on Unity?

Example:
- https://github.com/sschmid/Entitas-CSharp/issues/611

**Comment by herux** [comment]
I don't see NSpec can be used cross platform, can we use testsuite for mono ?
https://www.mono-project.com/community/contributing/test-suite
