### ISSUE TITLE
Collision: Sight Cone Test

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/kcg#504]
Collisions/SightConeTest.cs

1> A cone from a point

2> Tests if AABB or agents are in cone

3> Checks out to distance R
- so do circle test first

---

Make Note
- TODO: May call this before ray casting

---

- [x] AABB circle segment intersection
- [x] Test Scene

**Comment by mororo250** [comment]
- [ ] AABB circle segment intersection
- [ ] Test Scene
