### ISSUE TITLE
Wang: Code Cleanup

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/kcg#586]
Change namespace to "wang"

Then do Wang.Scene, Wang.EdgeTileSet, Wang.Scene

Organize
- Scene
- EdgeTileSet

Into own folders
- like Src/EdgeTileSet
- like Src/Scene
- like Src/Board

---

https://github.com/kk-digital/wang-tiles/blob/main/Entry.cs
- make file EdgeTileMap.cs
- class EdgeTileMap
- struct EdgeTileMapEntry

And put this in single file

---

Make source folder and put Scene stuff in Source/Scene?

https://github.com/kk-digital/wang-tiles/blob/main/SceneTile.cs

---

Move to Source/WangEdgeTileset?

https://github.com/kk-digital/wang-tiles/blob/main/TileSetDescription.cs
- rename. EdgeTileSetDescription

---

https://github.com/kk-digital/wang-tiles/blob/main/TileSpriteInformation.cs
- move?
- make comment what is using this?

---

https://github.com/kk-digital/wang-tiles/blob/main/UniquePixel.cs
- move to source/something?
- make comment what is using this

**Comment by mororo250** [comment]
Start doing this but there is some tasks. Its better for @choi303 and @zoubirabde9a  to do.

---

https://github.com/kk-digital/wang-tiles/blob/main/TileSpriteInformation.cs
- move?
- make comment what is using this?

---

https://github.com/kk-digital/wang-tiles/blob/main/UniquePixel.cs
- move to source/something?
- make comment what is using this

**Comment by choi303** [comment]
> Start doing this but there is some tasks. Its better for @choi303 and @zoubirabde9a to do.
> 
> Like these ones:
> 
> https://github.com/kk-digital/wang-tiles/blob/main/TileSpriteInformation.cs
> 
> * move?
> * make comment what is using this?
> 
> https://github.com/kk-digital/wang-tiles/blob/main/UniquePixel.cs
> 
> * move to source/something?
> * make comment what is using this

Comments Added. Folders Moved.
