### ISSUE TITLE
Importing UnityEngine remove UnityEngine

### ISSUE THREAD

**Issue by ketanba** [kk-digital/kcg#723]
If a file is importing UnityEngine remove UnityEngine

Put
//imports UnityEngine

at top of file

And have function "UnityEngine.Function" with unity engine typed out in full

**Comment by haltingstate** [comment]
1. You can use Unity Engine in script files. And Unity Asset files.

2. If its an obvious graphics/sound file and its all unity functions mostly, can just import unity

3. But some files, that only use it one or twice, we should stop the "using UnityEngine " thing

So we can refactor those parts of code into other areas.

If its a file that is doing with mostly or all UI functions and unity stuff, you can can just import Unity.UI
