### ISSUE TITLE
Unity: Set Render Pipeline to OpenGL

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/kcg#85]
Instructions here:
- https://docs.unity3d.com/Manual/OpenGLCoreDetails.html

1. Set unity to use OpenGl shader pipeline

2. Do a simple test for GLSL shader and see if they work

3. Make library for loading GLSL shaders and giving them an ID and reporting errors on loading
- put it in /src/game-engine?

https://docs.unity3d.com/Manual/SL-GLSLShaderPrograms.html

**Comment by choi303** [comment]
Unity GLSL shading examples:
 https://en.wikibooks.org/wiki/GLSL_Programming/Unity

**Comment by haltingstate** [comment]
Finished
