### ISSUE TITLE
Add Class for Camera information

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/kcg#86]
This might need some research to figure out how to do this
- create internal structures for camera/screen/system information
- grab system information once at start
- update camera information once per frame at beginning of frame and cache internally

Task: Camera System
- See Camera in: github.com/skycoin/cx-game
- See Camera in: https://github.com/Gnomescroll/Gnomescroll
-
We need to port functions to Assets/src/game-engine/camera

1. Camera information
- For now, get unity camera information
- Screen size / resolution
- Camera Matrix (position, rotation)
- Zoom
- X,Y,z position of camera

2. ScreenInformation
- Screen size / resolution
- aspect ratio, etc

3. System information
- GPU information, driver version and type, operation system, number of cores and so on
- see if there is easy unity function

- Save camera and this information to local struct in case we need it
- Port the frustum culling function from Gnomescroll

- Function for Checking if sphere is in camera frustum
- getting trapezoidal camera fulstrum (checks if point is within camera frustum)
- getting camera angle in X, camera angle Y  (the field of view in each dimension)

**Comment by choi303** [comment]
Unity does automatically cull objects not in the view frustum. Adding your own culling will only add more overhead.

**Comment by choi303** [comment]
Unity does by itself; you can see this in the game view stats as the draw calls go down when objects are no longer in view and aren't rendered any more. You won't get this effect in the editor scene view window, and thus won't get any performance benefits in the editor (except if you have the game view maximized, I suppose), but the only thing that actually matters is performance on the device itself.

**Comment by SkycoinSynth** [comment]
Resolved.
