### ISSUE TITLE
Port Physics For Player/Block Collisions:

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/kcg#90]
Cleanup and port these collision calculations to kcg from prototype
- https://github.com/skycoin/cx-game/blob/main/physics/collision.go
- https://github.com/skycoin/cx-game/blob/main/physics/body.go

- Port the physics from github.com/skycoin/cx-game
- For determining player collision with objects/map
- Use entity system to create components/entities for players /enemies~~
- Make note: that collision calculation should internally cache the chunks around player (up left, up right, bottom left, bottom right) instead of doing GetTile for each tile.
- Assume player is less than 16 blocks wide/tall
- Have a function for drawing the collision box of player (in red)
- Make Note: TODO: implement sphere collision
- Make Note: Find function for drawing collision lines for map tiles in cx-game
https://github.com/skycoin/cx-game/tree/main/render
https://github.com/skycoin/cx-game/blob/main/render/lines.go

- Cleanup up math code and split over multiple lines
- Math code is from gnomescroll

Make Note: Want to use elliptical/capsule collider eventually too, not just box collider
Make Note: Each Tile type has as collision type enum, determining collision behavior/lines
- put notes in comments, will fix later

Put Note
- TODO: add material type for block
- TODO: per material coefficient of restitution, coefficient of static friction and coefficient of dynamic friction

**Comment by Windings-Lab** [comment]
Making SAT collision
