### ISSUE TITLE
You can continue shooting while dead

### ISSUE THREAD

**Issue by Lonoress** [kk-digital/KCG#935]

**Comment by choi303** [comment]
We can't check every scenario before doing an action. We need Event System.

**Comment by choi303** [comment]
But we can check is agent alive or not before doing any action. Yeah, this is it.

**Comment by Lonoress** [comment]
I will check on PlayerInput.cs level for now but definitely should be on action manager level as its only a isAlive bool check

**Comment by choi303** [comment]
> I will add check on PlayerInput.cs level for now but definitely should be on action manager level as it's only a isAlive bool check

No worries I added the check. None of the actions are working unless agent is alive.

**Comment by Lonoress** [comment]
@choi303 If you dont mind ill take back this ticket as PlayerInput.IsGameplayBlocked() needs to be separate in two - one for UI and other for player character

**Comment by Lonoress** [comment]
Adding check in that method will resolve in 'nothing' working, which results in other bug

**Comment by choi303** [comment]
> @choi303 If you dont mind ill take back this ticket as PlayerInput.IsGameplayBlocked() needs to be separate in two - one for UI and other for player character

Okay but, make a new one please.

**Comment by Lonoress** [comment]
You pushed bugged version ?

**Comment by choi303** [comment]
> You pushed bugged version ?

Yes, https://github.com/kk-digital/KCG/commit/6327b8468350baeff7e5c45e37ec2fa903c69562.
